### ISSUE TITLE
Support Elastic 5

### ISSUE THREAD

**Issue by dmitrynovik** [ElasticLINQ/ElasticLINQ#100]
an expression

```csharp
_context.Query<T>().Where(x => x.Id == id).AsEnumerable().FirstOrDefault();
```

Generates the following request

```json
{"query":{"filtered":{"filter":{"term":{"_id":"AVhHuvPhIBJMsQlmQd8B"}}}},"timeout":"20s"}
```

which is no longer valid with Elastic 5

```json
{
  "error": {
    "root_cause": [
      {
        "type": "parsing_exception",
        "reason": "no [query] registered for [filtered]",
        "line": 1,
        "col": 22
      }
    ],
    "type": "parsing_exception",
    "reason": "no [query] registered for [filtered]",
    "line": 1,
    "col": 22
  },
  "status": 400
}
```

**Comment by jbravobr** [comment]
Firstly, congratulations for the work..
Any news about full support to ES 5? I need this asap and it is very complex to develop. Thanks.

**Comment by damieng** [comment]
I changed job last year and no longer use elasticsearch in my job so now it's a case of trying to find spare time to work on it.

**Comment by nmathur** [comment]
Hello damieng,

Can you please help me with following?

This query:
`_context.Query<Person>().Where(x => x.Age== 20 && x.City == "Jaipur").ToList();`

is generating this request (response is bad request 400)
```
{
  "query" : {    
      "and": [{
          "term": {
              "age": "20"
          }
      }, {
          "term": {
              "city": "Jaipur"
          }
      }]
    }
}
```
After reading [this](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/query-dsl-and-query.html) post I tried following request and it worked:
```
{
  "query" : {
    "bool" : {
      "must": [{
          "term": {
              "age": "20"
          }
      }, {
          "term": {
              "city": "Jaipur"
          }
      }]
    }
  }
}
```

Should I replace **AndCriteria** with **BoolCriteria (Must)** .. if yes then at which places?

**Comment by damieng** [comment]
Are you using the https://github.com/ElasticLINQ/ElasticLINQ/tree/elasticsearch5 branch?

**Comment by nmathur** [comment]
Sorry for late response .. Yes .. elasticsearch 5 .. and I am using elasticsearch 5.6

**Comment by damieng** [comment]
This has now been merged into master and seems to be working fine.
