### ISSUE TITLE
Couldn't find way to lowercase the typename and also disable pluralization

### ISSUE THREAD

**Issue by MrGorki** [ElasticLINQ/ElasticLINQ#101]
Using elastic search 1.7.6 + NEST 1.9.1 and it creates index as lowercase. 

So, queries going to the address below is not responding:
`http://localhost:9200/jobs/jobRecord/_search`

But this one responds;
`http://localhost:9200/jobs/jobrecord/_search`

Unfortunately; ElasticLINQ creates the first one with the below mapping settings:
`  var mapping = new ElasticMapping(camelCaseFieldNames: true, pluralizeTypeNames: false, camelCaseTypeNames: false);`

Is there anyway to make it lowercase?

**Comment by damieng** [comment]
Subclass TrivialElasticMapping and override the GetDocumentType

```csharp
public class CustomElasticMapping : TrivialElasticMapping {
  public override string GetDocumentType(Type type) {
    return base.GetDocumentType(type).ToLower();
  }
}
```

Then pass a new instance of TrivialElasticMapping into your ElasticContext to use it e.g.

```csharp
var db = new ElasticContext(connection, new CustomElasticMapping());
```

**Comment by MrGorki** [comment]
Thanks! Thats what I was looking for :)

**Comment by MrGorki** [comment]
Ohh. But pluralization persists. Is it possible to send pluralization parameter also?

**Comment by MrGorki** [comment]
Sorry for inconvenience returning `type.Name.ToLower();` should fix this problem.
