### ISSUE TITLE
How to search collections without .Any()

### ISSUE THREAD

**Issue by MrGorki** [ElasticLINQ/ElasticLINQ#102]
I want to find a way to express the query below. I will appreciate if you show me some direction:
 
`var result = jobs.Where(y => y.Addresses.Any(m => m.City.Id == query.Id));`

**Comment by MrGorki** [comment]
I think it is related to: https://github.com/CenturyLinkCloud/ElasticLINQ/issues/81

**Comment by AlexzundeR** [comment]
Yes, you are right! My pull request https://github.com/CenturyLinkCloud/ElasticLINQ/pull/82 fix this moment. This solution greatly works in my project.

**Comment by MrGorki** [comment]
@AlexzundeR Great! Is it merged to the dev branch or we have to use your rep?

**Comment by AlexzundeR** [comment]
My PR have not been pulled and I don't know why. And there is no that changes In my repo.. One thing that you can try to do, use sources of ElasticLinq in your project, copy changes from PR to you project copy, and use it.

**Comment by MrGorki** [comment]
I will try for sure. Thanks!!!

**Comment by damieng** [comment]
The reality is it was only me working on it and my day job no longer involves Elasticsearch or LINQ.

**Comment by MrGorki** [comment]
It is totally understandable. Is it possible to merge that PR at least? or can affect other stuff?

**Comment by MrGorki** [comment]
OK. I've add the code. It works but firing an error when combined with null check like below.

`var result = jobs.Where(y => y.Addresses.Any(m => m.City != null && m.City.Id == query.Id));`

**Comment by damieng** [comment]
I didn't merge the PR as it special-cased the Any pattern by way of its own FieldCallCriteria instead of simply traversing down into Any methods and reuse the existing operation-to-criteria mappings.

If it had done that then null would have worked. As it is the PR hard-coded it to check for Terms (null uses Exists)
