### ISSUE TITLE
Migrate low level code to Elasticsearch.NET

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ElasticLINQ/ElasticLINQ#103]
We use https://github.com/elastic/elasticsearch-net. We use ElasticSearch as search and as audit NoSQL storage.  We need LINQ something for audit, but it is not enough to justify referencing https://github.com/CenturyLinkCloud/ElasticLINQ. We would need to map entities and do initialization code 2 times. Given  https://github.com/elastic/elasticsearch-net is 6 time popular and official, could https://github.com/CenturyLinkCloud/ElasticLINQ start migrating low level initialization code to https://github.com/elastic/elasticsearch-net. So we may share at least initialization.

**Comment by damieng** [comment]
I'm not sure what you mean by "low-level initialization code" and also we don't have the ability to add code to somebody elses product (elasticsearch.net)

To be able to turn LINQ queries into ES queries requires some logic in our own mapping layers that is not readily available in Elasticsearch.NET

You can today however use an Elasticsearch.NET connection to run the queries.

**Comment by dzmitry-lahoda** [comment]
ElasticLINQ has BaseElasticConnection.cs, ElasticConnection.cs, ElasticConnectionOptions.cs, IElasticConnection.cs. Elasticsearch.Net has IConnectionConfigurationValues.cs, ConnectionConfiguration.cs, IConnection.cs, IConnectionPool.cs, IElasticLowLevelClient.cs. Given I already use Elasticsearch.Net, I need to initialize ElasticLINQ using same values, but different code. Would we easy to use  ElasticLINQ if it to depend upon Elasticsearch.Net.

ElasticLINQ  has NotAnalyzedAttribute.cs, IElasticMapping.cs. NEST has https://github.com/elastic/elasticsearch-net/tree/master/src/Nest/Mapping, FieldIndexOption.cs.  Given I already use NEST, I need to add second mapping for ElasticLINQ, but with same meaning. Would we easy to use  ElasticLINQ if it to depend upon NEST.

Given Elasticsearch.Net/NEST is 6 times popular of ElasticLINQ I would be fined to depend on them and ease usage of LINQ where it is fine.

I have build my own LINQ to NEST for my specific purpose, but it would be great to have ElasticLINQ to NEST so I could reuse some LINQ related stuff in my provider. 

ES API is several times larger then LINQ and no one LINQ fits it all. I expect to have many LINQ providers depending of how data is stored/configured in ES. NEST is one to one to all ES features, strongly typed and with optimizations of NEST queries. So it is good base to build LINQ provider above.

**Comment by dzmitry-lahoda** [comment]
I suggest to reopen issue for a while. Wait some people to vote/comment to make it more clear what I propose.

**Comment by dzmitry-lahoda** [comment]
Also relaying on NEST will ease migration on new version of ES as NEST handles compatibility(e.g. HTTP call of scroll changed from 1.x to 2.x, but NEST not) or shows obsolete warnings, unlike pure JSON.

**Comment by dzmitry-lahoda** [comment]
I have already built LINQ above nest https://github.com/elastic/elasticsearch-net/issues/2522

**Comment by dzmitry-lahoda** [comment]
Same request is my  https://github.com/elastic/elasticsearch-net/issues/1197#issuecomment-69453477
