### ISSUE TITLE
Any way to override document type name used to generate URL?

### ISSUE THREAD

**Issue by sgarg7** [ElasticLINQ/ElasticLINQ#104]
I need the URL to be 

http://myeshost.com:9200/cat_activities_20170116/_Cat/_search

but I'm getting

http://myeshost.com:9200/cat_activities_20170116/_Cats/_search

since the class name is Cat.

Is there any way I can override the URL used?

**Comment by damieng** [comment]
Yes, you can change this - duplicate of #101
