### ISSUE TITLE
Object initializer support for Select

### ISSUE THREAD

**Issue by jdfrank** [ElasticLINQ/ElasticLINQ#106]
For testing purposes, I made a class with a very minimal subset of WebUser's fields. This projection code throws the same error as the previous GroupBy issue.

                var wu = ctx.Query<WebUser>().Where(x => x.Forename == "Emily").Select(x => new WebUserSummary()
                {
                    Id = x.Id,
                    Forename = x.Forename,
                    Surname = x.Surname,
                    Phone = x.Phone,
                    Email = x.Email,
                    Username = x.Username

                }).ToList();

If this is not immediately repeatable, please let me know so that I can attempt to isolate additional variables.

Thanks in advance.

**Comment by damieng** [comment]
So the reason this is happening is that the partial evaluator which runs through the query first to find branches it can do invoke locally to turn into a constant value before translating the query is thinking that `new WebUserSummary()` doesn't rely on any parameters and can be therefore optimized. (If you add a constructor to it that takes a single arg for example then the rest of the query happily runs)

The evaluator needs to be updated to take the entire object initializer pattern into consideration when looking at such branches.

**Comment by damieng** [comment]
Additionally the main code paths do not recognize the object initializer pattern so in the case of the example you'll get a cast error as it was expecting WebUser not WebUserSummary and so has not rebound all the individual fields nor created a materializer for the new type.

The simplest workaround which probably works with both LINQ to SQL and ElasticLINQ is to put the body of the Select into a method or to put an AsEnumerable before it.  Obviously if you are selecting a whole lot of fields that is going to defy the point of only bringing back a few.

Anonymous projections should also work in both, map correctly and only select the right fields.

**Comment by damieng** [comment]
Thankfully the rebinding code was very flexible and well-written so the second part just turned out to be a 2-liner.

There is a branch up at https://github.com/ElasticLINQ/ElasticLINQ/tree/object-initializer-support that should work for this. Let me know if it does/doesn't for you.

**Comment by jdfrank** [comment]
I am no longer getting the previous error, but now there is a different bug, this one having to do with nullable types: Expression of type 'System.Nullable`1[System.Int32]' cannot be used for parameter of type 'System.Object' of method 'Int32 ToInt32(System.Object)'

In our object initialization, our base object has a number of nullable integers that we convert with Convert.ToInt32() calls. I'm digging in the code to see if we can add a cast somewhere...

One other bit of information, the error does not occur if the new object field is also nullable.

**Comment by damieng** [comment]
Would need a new issue with minimal repro.

**Comment by damieng** [comment]
Fixed in #107

**Comment by damieng** [comment]
Shipped in 1.4.3 now on NuGet.
