### ISSUE TITLE
Nullable Field Handling During Object Initialization

### ISSUE THREAD

**Issue by jdfrank** [ElasticLINQ/ElasticLINQ#108]
For testing purposes, I made a WebUserSummary class with a very minimal subset of WebUser's fields. I also added a nullable integer field to WebUser called TestField. This field simply returns the WebUser Id field. The Id field on WebUserSummary is not nullable. 

```csharp
var wu = ctx.Query<WebUser>().Where(x => x.Forename == "Emily")
   .Select(x => new WebUserSummary {
	Id = Convert.ToInt32(x.TestField)
}).ToList();
```
The exception is:
>Expression of type 'System.Nullable`1[System.Int32]' cannot be used for parameter of type 'System.Object' of method 'Int32 ToInt32(System.Object)'

**Comment by damieng** [comment]
Right now we don't support putting methods in the select projections and this is a non-trivial thing to add. At first glance you would imagine we could wrap the entire select lambda up and then call it with instances of WebUser to do the right thing but that would break the field selection system (when you do x.TextField we just select 'textField' so we never have a WebUser to be x)
