### ISSUE TITLE
How to set the type name?

### ISSUE THREAD

**Issue by xplatsolutions** [ElasticLINQ/ElasticLINQ#112]
I was searching for a while without luck, I need to set the type of the document to something different than the default `typeof(CodesAntiTheftDeviceModel).Name`.

I have the below example.

```
var elasticSearchUri = new Uri("host");
ElasticConnection elasticConnection = new ElasticConnection(elasticSearchUri, index: alias);
ElasticMapping elasticMapping = new ElasticMapping(false, false, false, false);
ElasticContext = new ElasticContext(elasticConnection, elasticMapping);
```

In a method.

`var linq = await ElasticContext.Query<CodesAntiTheftDeviceModel>().ToListAsync();`

ElasticContext ends up with the following Uri, http://host/alias/CodesAntiTheftDeviceModel/_search, but in ElasticSearch type name is antitheft_device_code.
I will need to have http://host/alias/antitheft_device_code/_search, any ideas?

**Comment by damieng** [comment]
The ElasticContext constructor can take an object that implements IElasticMapping which is responsible for figuring out all typenames, property names etc. By default it instantiates a TrivialElasticMapping which does some things like camel casing etc.

I'd recommend starting with subclassing TrivialElasticMapping and just overriding what you need, e.g.

```csharp
public class CustomElasticMapping : TrivialElasticMapping {
  public override string GetDocumentType(Type type) {
    if (type.Name == "CodesAntiTheftDeviceModel") return "antitheft_device_code";
    return base.GetDocumentType(type).ToLower();
  }
}
...
var context = new ElasticContext(..., new CustomElasticMapping());
```

**Comment by xplatsolutions** [comment]
That is a workaround I can use for now but it would be nice to add something simpler so we can use in a base repository while creating the options/context or even a SetDocumentType(Type, string) method with holding internally a dictionary to resolve in runtime.

Thank you for your quick response.

**Comment by damieng** [comment]
The IElasticMapping interface lets you plug-in whatever mechanism you like.  You could easily change the above example to use a dictionary and expose a SetDocumentType method on it to add to that dictionary.

**Comment by xplatsolutions** [comment]
It's sufficient, it worked great!
