### ISSUE TITLE
FirstOrDefaultAsync not working

### ISSUE THREAD

**Issue by xplatsolutions** [ElasticLINQ/ElasticLINQ#113]
I have the following code.

```
public async Task<CodesFilterModel> GetColumnFilterCodesWithSubscriberIdAsync(string subscriberId)
{
    var result = await ElasticContext.Query<CodesFilterModel>().FirstOrDefaultAsync(p => p.SubscriberId == subscriberId);
    return result;
}
```

The above is not working, returns null. If I change to the below works fine but of course it is not performance wise.

```
public async Task<CodesFilterModel> GetColumnFilterCodesWithSubscriberIdAsync(string subscriberId)
{
    var result = await ElasticContext.Query<CodesFilterModel>().ToListAsync();
    var first = result.FirstOrDefault(p => p.SubscriberId == subscriberId);
    return first;
}
```

Any ideas?

**Comment by damieng** [comment]
What kind of field is subscriber id? If it is a string then you'll find that elasticsearch doesn't match strings in the way you might expect.  There is more detail at https://github.com/ElasticLINQ/ElasticLINQ/wiki/Important-things-to-know-about-Elasticsearch but the short of it is you'll need to put [NotAnalyzed] attribute on your CodesFilterModel class SubscriberId property.

**Comment by xplatsolutions** [comment]
Is there any other way instead of adding attributes related to ElasticSearch in my POCOs?

**Comment by damieng** [comment]
I would try [NotAnalyzed] first just to make sure that is the actual problem.

If that solves the problem then you can override FormatValue in your ElasticMapping subclass and choose when to perform the necessary ToLower or not on the field.  

https://github.com/ElasticLINQ/ElasticLINQ/blob/master/Source/ElasticLINQ/Mapping/ElasticMapping.cs#L82

**Comment by xplatsolutions** [comment]
Added [NotAnalyzed] attribute but still doesn't work.

```
public class CodesVehicleSpecificCoverageModel
{
    [NotAnalyzed]
    public string InsuranceCompany { get; set; }
    public string CoverageType { get; set; }
}

public async Task<IEnumerable<CodesVehicleSpecificCoverageModel>> GetAllVehicleSpecificFiltersWithSubscriberIdAsync(string subscriberId)
{
    //QueryContainer query = new TermQuery
    //{
    //    Field = "SubscriberId",
    //    Value = subscriberId
    //};

    //ISearchRequest searchRequest = new SearchRequest
    //{
    //    Query = query
    //};

    //var searchResults = await ElasticClient.SearchAsync<CodesVehicleSpecificCoverageModel>(searchRequest);

    //return searchResults.Documents;

    var documents = ElasticContext.Query<CodesVehicleSpecificCoverageModel>()
                                       .Where(p => p.InsuranceCompany == subscriberId);
    return await documents.ToListAsync();
}
```

I have commented the ElasticClient code that works.

Find below how a document looks like in the database.

```
{
        "_index": "coverageverifier_vehicle_specific_filters_2017_03_24",
        "_type": "vehicle_specific_filter",
        "_id": "AVsC5XSQ4_1_7gwhCRl8",
        "_score": 1.0,
        "_source": {
          "InsuranceCompany": "A007",
          "CoverageType": "COLL",
          "EffectiveDate": "2014-04-17T19:09:54.151Z",
          "ExpirationDate": null
}
```

When we import the data, should we mark the property as NotAnalyzed; since I didn't import the data this might be something to consider and do for querying properties.

**Comment by damieng** [comment]
Can you get the schema by doing a GET /_all/_mapping/vehicle_specific_filter and let me know what the InsuranceCompany field is specified as?

**Comment by xplatsolutions** [comment]
Here you are, i just checked and it actually is as not_analyzed.

```
// 20170403170459
// http://uwsearcht.verisk.com/coverageverifier_vehicle_specific_filters

{
  "coverageverifier_vehicle_specific_filters_2017_03_24": {
    "aliases": {
      "coverageverifier_vehicle_specific_filters": {
        
      }
    },
    "mappings": {
      "vehicle_specific_filter": {
        "properties": {
          "CoverageType": {
            "type": "string",
            "index": "not_analyzed"
          },
          "EffectiveDate": {
            "type": "date",
            "format": "strict_date_optional_time||epoch_millis"
          },
          "ExpirationDate": {
            "type": "date",
            "format": "strict_date_optional_time||epoch_millis"
          },
          "InsuranceCompany": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      }
    },
    "settings": {
      "index": {
        "creation_date": "1490402223650",
        "number_of_shards": "1",
        "number_of_replicas": "0",
        "uuid": "2YTormkySMGvHxXcdv2FHg",
        "version": {
          "created": "2030599"
        }
      }
```

**Comment by damieng** [comment]
In that case I can only suspect that the field name it is generating is wrong. By default it uses camel-case which you can switch off by adding this to your MyElasticMapping;

```csharp
public MyElasticMapping() : base(false, true, true, true, EnumFormat.String, null) { }
```

(The second arg now false will stop camel-casing).  If that doesn't work you can take a look at the query that is being generated:

```csharp
var query = await ElasticContext.Query<CodesFilterModel>()
    .Where(p => p.SubscriberId == subscriberId);
var queryInfo = query.ToQueryInfo();
```

Set a breakpoint on the queryInfo line and step over and you'll see Uri and Query properties on it which should make it obvious what it is doing.

**Comment by xplatsolutions** [comment]
Success! 
It works and it doesn't need the attribute [NotAnalyzed].

Great help this library, thank you.
