### ISSUE TITLE
Connection to multiple hosts.

### ISSUE THREAD

**Issue by rafamerlin** [ElasticLINQ/ElasticLINQ#118]
Hello,

Is it possible to connect to multiple hosts? 

For example, I have a cluster running ES that has these addresses:
http://search1.internal:9200
http://search2.internal:9200
http://search3.internal:9200

They are all part of the same cluster, and when I tried to run performance tests in my app (running a massive amount of queries against the app) ES stopped responding. I reckon that the reason is that we connect only to search1 which is the master node so it ended up "breaking" the machine.

I will try to add a load balancer to fix this issue, but I just would like to know if ElasticLinq has the functionality to connect to a cluster (pointing in the connection all the hosts in that cluster).

Cheers

**Comment by damieng** [comment]
I believe if you use the Elastic.NET connector instead of using ElasticLINQ's direction connection it should be able to support this although I haven't tried it myself.

**Comment by damieng** [comment]
i.e. this https://github.com/ElasticLINQ/ElasticLINQ/blob/master/Source/ElasticLINQ.ElasticsearchNet/ElasticNetConnection.cs which can take an IElasticClient object from ElasticSearch.NET 1.x

**Comment by rafamerlin** [comment]
I ended up creating a load balancer and using it. Because I can't use Elastisearch.net as I'm still in ES 1.4.5 and dotnet core (ElasticSearch.net for this version does not support dotnet core as far as I know).

Thanks anyway
