### ISSUE TITLE
ElasticMethods.ContainsAny does not format array elements

### ISSUE THREAD

**Issue by troyschneringer** [ElasticLINQ/ElasticLINQ#12]
I have an array `["FOO"]` which I would have expected to get formatted as `["foo"]` but it does not do the lowercase on the element.

**Comment by troyschneringer** [comment]
This appears to be an issue because my array is a collection of objects that are not strings but have a `JsonConverter` and both implicit and explicit operators to/from `string`

**Comment by bradwilson** [comment]
Fixed in 07fb247e5167bad8b93134cb65a03053a352687f
