### ISSUE TITLE
How to pass DocumentType at the time of query

### ISSUE THREAD

**Issue by nmathur** [ElasticLINQ/ElasticLINQ#125]
This is not an issue .. this is a question .. I am trying to implement ElasticLINQ to my existing project and my document types are in lower case .. 

Like below:
CustomerInfo is customerinfo
Employee is employee 

I looked into the source and unable to find any way to pass DocumentType manually .. is this implemented and I am not able to find .. or it is not implemented? .. if it is possible then please share how?

Thanks in advance.

**Comment by damieng** [comment]
There is an object you can pass to the constructor of type IElasticMapping that is used to determine how field and document names are mapped.  You can then just override the GetDocumentType method, e.g.

```csharp
public GetDocumentType(Type documentType) {
  return documentType.Name.ToLower();
}
```

You can see more examples and implementations https://github.com/ElasticLINQ/ElasticLINQ/tree/master/Source/ElasticLINQ/Mapping

**Comment by nmathur** [comment]
Thank you so much for quick response ..

I will implement that .. I have one more question, what if the type name is completely different .. e.g, CustomerAccounts is "custaccount" ... do we have any option to pass the type at the time of query .. ?

Please reply.

Thanks in advance.

**Comment by damieng** [comment]
The best thing to do there is would be to have an ElasticMapping class that has a dictionary.  You can either hard-code the values or allow registration at run-time.  e.g.

```csharp
public DictionaryElasticMapping : ElasticMapping
...
  private Dictionary<Type, String> documentTypes = new Dictionary<Type, String>();
  public GetDocumentType(Type documentType) {
    return documentTypes[documentType];
  }

  public AddDocumentType(Type documentType, string documentTypeName) {
    documentType[documentType] = documentTypeName;
  }
}

**Comment by nmathur** [comment]
@damieng thank you so much ... sorry for asking too much questions here .. but please answer one more question .. I am working on elasticsearch 5.6 .. 

This works fine
`context.Query<DemoModel>().ToList()`

But this is failing:
`context.Query<DemoModel>().Where(p => p.City == "Jaipur").ToList();`

You mentioned [here](https://github.com/ElasticLINQ/ElasticLINQ/pull/105) that these basic operations are supported .. but I am getting "Argument does not match" ... time-out ... etc .

Is this version related issue? ...

**Comment by damieng** [comment]
You'll need to use the https://github.com/ElasticLINQ/ElasticLINQ/tree/elasticsearch5 branch which has some experimental Elasticsearch 5 support.  I only ever worked with ES 1.x at my job and my new job does not involve ES at all and so development is kind of at a standstill unless people want to contribute.

That said it was very stable on 1.x and the main missing feature on the ES5 branch is GroupBy has been removed (it mapped to Facets in ES 1.x but they were removed in ES5 and replaced by Aggregates).

**Comment by nmathur** [comment]
Thanks for sharing the link and developing such a great tool .. would love to contribute 👍

**Comment by nmathur** [comment]
Hello damieng,

Can I add your project (ElasticLinq) to my project  .. is this legal?

**Comment by damieng** [comment]
What do you mean add it to your project?  What kind of project is it?  Normally you just take a dependency on libraries such as this.

**Comment by nmathur** [comment]
I am applying changes to your project as you suggested .. I added the reference to my project with this path of your library:

....ElasticLINQ\Source\ElasticLINQ\bin\Debug

Now when I shifted my code to another machine the library is looking for exact path .. which is not available in new machine ....

**Comment by damieng** [comment]
You can just use the ElasticLINQ from NuGet.  Add a class that inherits from ElasticMapping to your own code with the necessary GetDocumentType. 

There is no need to modify the ElasticLINQ library to do this.

**Comment by nmathur** [comment]
ok .. thanks for explanation .. I will do that.
