### ISSUE TITLE
Is the library discontinued?

### ISSUE THREAD

**Issue by xplatsolutions** [ElasticLINQ/ElasticLINQ#126]
I just want to understand if the project is still on-going, ES v6 is out and v5 is still under development. It's a shame because it was working nicely :-/

**Comment by damieng** [comment]
The problem is that Elastic keep breaking their query api between versions and that I no longer work for a company that uses this library so any time I spend on it has to be from what little free time I have.  If people want to help together we could keep pushing it forward.

**Comment by xplatsolutions** [comment]
Makes sense.
