### ISSUE TITLE
Appears to hang when querying latest version of ES (6.2.4) [simple fix]

### ISSUE THREAD

**Issue by lesscodetxm** [ElasticLINQ/ElasticLINQ#128]
Examining the request in Fiddler, seems like the Content-Type sent is not acceptable to ES:

{"error":"Content-Type header [text/plain; charset=utf-8] is not supported","status":406}

I'm able to force the Content-Type to "application/json" (ElasticConnection.cs, line 112) and it seems to work just fine with that.

I also converted the main project to .NET Core without any apparent issues, so that's good.

**Comment by damieng** [comment]
The header should definitely be fixed for all versions. I can either do that or if you want you could create a PR.

The .NET Core - what version are you thinking? Right now you can use the project as-is because it's PCL but there should probably be some migration.  Can do this for v5+

v6 itself isn't yet supported - the url changing and no longer supporting multiple types per index requires a bit of thought about the conventions to use.  I'd be interested to hear your thoughts on this.

**Comment by lesscodetxm** [comment]
We're brand new with Elasticsearch so I'll play around with my local fork for a while, against our ES6 instance, and see if anything comes up. We're basically using ES only for Serilog, so I don't think we need to care about multiple types per index? I think everything will look like a "logevent", with some destructured context objects embedded inside. I hope this will work because it will make our lives a lot easier to be able search through an IQueryable. I'm also not anticipating anything too complex in terms of the Linq queries - just simple filtering on properties.

We're in a phase of migrating as much as we can to latest .NET Core (2.2) so that we can run our REST services on Linux, so I just automatically did the conversion when I saw the project targets 4.6.X - I didn't notice the PCL. I literally just copied the source files into a new Core class library project and it worked immediately, which was very cool. I suppose if we wanted to do this properly we'd make a .NET Standard library that targets an appropriate level?

**Comment by damieng** [comment]
It's not just caring about multiple types per index, the url format changes because they no longer support it.

I'd rather we switch from .NET PCL to .NET standard than target .NET core directly. It opens up more possibilities with little trade-off.

**Comment by damieng** [comment]
I started the ES5 changes a while back but they're definitely not complete.  I just checked out the breaking changes - and boy do Elastic like to break the query syntax every single major release - and there are definitely a whole bunch of queries that still aren't going to work.

https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_search_changes.html

**Comment by lesscodetxm** [comment]
I'm about halfway through converting our log event reporting to use ElasticLinq instead of EF Core, and there's only been a couple of things so far I've had to break up into separate phases because EL didn't support it (eg, GroupBy, Join, Distinct). In places where performance is important (eg Distinct) we'll probably end up converting over to the native Elasticsearch.NET DSL anyway.

So far EL has been a big help in allowing us to keep an IQueryable paradigm for our reporting and unit tests while we refactor our cleaner logging approach. I'll keep an eye out for broken queries, and maybe try to learn a bit about the implementation as I'm debugging. I've done custom LINQ query providers before so I know how complex this can be. I was actually about to start writing another one for this until I found your package :-)

**Comment by damieng** [comment]
GroupBy used to work with Elasticsearch by converting it all to facets but then Elastic removed them in favor of Aggregates so I had to remove it.

**Comment by lesscodetxm** [comment]
Wow, they're really not into backward compatibility, are they?

**Comment by damieng** [comment]
This project is no longer active so I am closing all old issues.
