### ISSUE TITLE
.NET Standard Support

### ISSUE THREAD

**Issue by casperOne** [ElasticLINQ/ElasticLINQ#130]
Is support for .NET Standard in the works?

**Comment by Jlalond** [comment]
@damieng would you mind if I switched everything over to standard 2.0 at this point? Is there any peer dependencies that I don't see that require 4.5?

**Comment by damieng** [comment]
Go for it!

**Comment by Jlalond** [comment]
@damieng so far things are going good. The issues I'm encountering are around the new ElasticSearch.Net packages as many of the accessory methods are gone now (Create in ElasticSearchResponse is a good example), now I haven't done much research on my end but it looks like the first .net standard impl of `ElasticSearch.Net` is [2.4.1](https://www.nuget.org/packages/Elasticsearch.Net/2.4.1). Do you want to bake the update into moving to net standard as well?

**Comment by damieng** [comment]
Sure, we can do that.  

My only concern is whether ElasticSearch.Net supports Elastic 5 or not.  This library doesn't work with 6 because of the whole dropping of types.

**Comment by Jlalond** [comment]
2.3.1's dependencies 
![image](https://user-images.githubusercontent.com/25160653/68598454-d7b27f80-046c-11ea-9bd3-4a3641a285d7.png) makes me believe so.

The big issue is `IElasticClient` no longer exists, as we have the low level client and then the nest client. 

(Also why did ES get rid of types :/, I'll never understand. )

**Comment by damieng** [comment]
This project is no longer active so I am closing all old issues.
