### ISSUE TITLE
Multiple contains in a query is not working

### ISSUE THREAD

**Issue by nmathurbkn** [ElasticLINQ/ElasticLINQ#131]
This is not an issue. This is a query.

Below query is not working, please share suggestions:

db.Query<People>().Where(p => p.Tags.Contains(keyword) || p.State.Contains(keyword));

Thanks in advance.

**Comment by damieng** [comment]
Does it come back with an error, or does it generate an incorrect query?

**Comment by nmathurbkn** [comment]
I am not sure if the query is incorrect, but I am getting the common error message about maximum retries. I get this error message when by mistake I pass wrong field name. But this time the field names are correct.

**Comment by damieng** [comment]
If you cast your Query to ElasticQuery and then call `ToQueryInfo().Query` you can see what Elastic query it will send.  Hopefully that will shed light on the problem.

**Comment by nmathurbkn** [comment]
Hello damieng, 

Thanks a lot for quick response. Here I am sharing the query:
```
{ 
   "query":{ 
      "or":[ 
         { 
            "query_string":{ 
               "query":"*David*",
               "fields":[ 
                  "name"
               ]
            }
         },
         { 
            "query_string":{ 
               "query":"*David*",
               "fields":[ 
                  "fatherName"
               ]
            }
         }
      ]
   },
   "timeout":"10s"
}
```


This is my code:
`   IQueryable<Employee> query = context.Query<Employee>()
              .Where(x => x.Name.Contains(keyword) || x.FatherName.Contains(keyword)).AsQueryable();`

**Comment by damieng** [comment]
This project is no longer active so I am closing all old issues.
