### ISSUE TITLE
Which paging mode is used?

### ISSUE THREAD

**Issue by softlgl** [ElasticLINQ/ElasticLINQ#134]
Which paging mode is used?
from + size or scroll or search_after?

**Comment by damieng** [comment]
It uses `from` and `size` .

**Comment by softlgl** [comment]
Thank you for answering，ElasticLINQ looks very powerful，Are there any plans to upgrade to. Netstandard2.0？

**Comment by damieng** [comment]
What version of Elastic are you using?

**Comment by softlgl** [comment]
we uses 6.x and 7.x

**Comment by damieng** [comment]
Unfortunately this provider only works correctly with Elastic 1.x and 2.x - the query syntax changed in breaking ways in 6.x and the removal of types in ES and forcing one-type-per-index broke the object type mapping mechanism as well.
