### ISSUE TITLE
Add support for administrative APIs

### ISSUE THREAD

**Issue by bradwilson** [ElasticLINQ/ElasticLINQ#16]

**Comment by fdsmax** [comment]
Hi, any update on when the Write APIs would be available to create, update and delete the indexes. We are planning to use ElasticLinq for our site http://thulya.com . Thanks and regards - Thulya Team.

**Comment by damieng** [comment]
We want to add this to ElasticLINQ (hence the issue) but none of the work for this has yet been started as it's not high-pri for us yet.

**Comment by damieng** [comment]
This should happen by layering on top of Elasticsearch.NET or not at all.

**Comment by AlexzundeR** [comment]
It would be nice to place on top of Elasticsearch.Net, I think. It would be more standardize.
