### ISSUE TITLE
Searches without an index but with a document type create incorrect URL

### ISSUE THREAD

**Issue by bradwilson** [ElasticLINQ/ElasticLINQ#17]
Based on reading the [search API](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-search.html) docs, we should have four URL patterns:

No index, no document type: `http://server:9200/_search` or `http://server:9200/_all/_search`
Index, no document type: `http://server:9200/index/_search`
No index, document type: `http://server:9200/_all/docType/search`
Index, document type: `http://server:9200/index/docType/search`

**Comment by damieng** [comment]
Appears to work fine now, possibly fixed during the Formatter work.
