### ISSUE TITLE
Allow custom field formatting via IElasticMapping

### ISSUE THREAD

**Issue by damieng** [ElasticLINQ/ElasticLINQ#2]
Right now values sent to ElasticSearch are ToLowered in order to work with the default analyzer however for not_indexed fields or for different languages different behavior might be required on a case-by-case basis.

Recommend:
1. Creating a NotAnalyzed attribute
2. Adding a GetFormattedFieldValue(PropertyInfo) method to IElasticMapping
3. Remove the RequestFormatter.Format method and replace it with a call to GetFormattedFieldValue earlier in the transformation

The method would just ToString the value if the PropertyInfo has NotAnalyzed or ToLower it if not.

**Comment by bradwilson** [comment]
This should basically be moving RequestFormatter.FormatTerm out onto the mapper. This not only allows pluggability for the lowercasing (including skipping things like that for non-materialized fields), it also allows special serialization handling since it returns JToken.

**Comment by bradwilson** [comment]
Shipped in 07fb247e5167bad8b93134cb65a03053a352687f.
