### ISSUE TITLE
Support .Contains for strings

### ISSUE THREAD

**Issue by bradwilson** [ElasticLINQ/ElasticLINQ#20]
(From a comment on my blog post)

``` C#
ElasticConnection connection = new...
ElasticContext context = new...
var r = from obj in context.Query() where obj.Text.Contains("hello");
```

I got NotSupportedException:
Unknown Where predicate 'obj.Text.Contains("hello")' in ElasticQueryTranslator.VisitWhere

**Comment by damieng** [comment]
I'm not sure what this would map to as ElasticSearch doesn't have a substring match that maps to contains/like. Open to suggestions.

**Comment by bradwilson** [comment]
The right way is probably to use `QueryString` instead of `Where` with `Contains`.

**Comment by bradwilson** [comment]
https://github.com/CenturyLinkCloud/ElasticLINQ/commit/dbfb93797e5207aa0f0a0c15888793b588775bfa
