### ISSUE TITLE
Any chance you can support Count?

### ISSUE THREAD

**Issue by dashkan** [ElasticLINQ/ElasticLINQ#21]
Would be great if support for Count was added. Using a package that is expecting Count and ElasticLinq is throwing a NotSupportedException.

**Comment by damieng** [comment]
Aggregates such as count have been started and are included in the dev branch however it only recognizes the .GroupBy() pattern right now so you could do:

`customers.GroupBy(g => 1).Select(g => g.Count())`

but can't yet do

`customers.Count();`

  I'll try and get some time to spend on the non-GroupBy operations this weekend.

**Comment by damieng** [comment]
Closed as duplicate of https://github.com/CenturyLinkCloud/ElasticLINQ/issues/5
