### ISSUE TITLE
null values in .Contains treated incorrectly

### ISSUE THREAD

**Issue by bradwilson** [ElasticLINQ/ElasticLINQ#22]
When you write a simple null check:

```
query.Where(x => x.id == null)
```

That gets correctly translated into:

```
{"missing":{"field":"id"}}
```

However, if the null value is a member of a collection, and the .Contains feature is used:

```
query.Where(x => ListOfIDs.Contains(x.id))
```

Then the null value is placed into the `terms` query:

```
{"terms":{"id":["1","2","3",null]}}
```

This is not legal with Elasticsearch (and results in a 400 when the request is issued).

**Comment by damieng** [comment]
I'd suggest the following:
- within a query we throw an error as we can't do a missing there.
- within a filter we convert this to an "or" filter that has a "term" with all non-values part and a "missing" that handles the null check.

Entity Framework also goes down the OR route   (x.Field IN (1,2,3) OR x.Field IS NULL)
