### ISSUE TITLE
Add support for async

### ISSUE THREAD

**Issue by bradwilson** [ElasticLINQ/ElasticLINQ#24]
It would be nice to follow in the path of EF and support async ToXxx operations (f.e., ToListAsync). Since ElasticLINQ's network protocol (HTTP) is implicitly async, it would be nice to allow better resource usage on servers by fully embracing that instead of hiding it behind LINQ's synchronous methods.

**Comment by prabhu** [comment]
+1

From my benchmark, I find NEST to be around 10 - 15% faster compared to ElasticLinq. Things like connection pooling, asynchronous api are helping NEST. Now that the .Net part is separate, it will be great if ElasticLinq could be re-written to use Elasticsearch.Net?

**Comment by prabhu** [comment]
fyi, we rewrote mongojs to use mongodb-core recently

**Comment by damieng** [comment]
ElasticLINQ would always be a little slower as it has to walk and evaluate a query tree.  That said we have discussed replacing the lower levels with Elasticsearch.Net for better integration/compatibility/ease of use. I think it's a good idea, just need some time to work on it.
