### ISSUE TITLE
Add ElasticContext.QueryRaw<T>

### ISSUE THREAD

**Issue by bradwilson** [ElasticLINQ/ElasticLINQ#3]
Allow the user to specify a raw ElasticSearch query, but still leverage the type mapping for the results.

**Comment by damieng** [comment]
Some considerations here:
1. Take the input as JObject to discourage string-building
2. Do we want to detect facets or field queries to appropriately deserialize

**Comment by damieng** [comment]
Given the considerations above will close until we get some specific real world use cases to support.
