### ISSUE TITLE
Lowercasing of field and type names

### ISSUE THREAD

**Issue by adam-drewery** [ElasticLINQ/ElasticLINQ#32]
Hi,

I have started getting acquainted with this library as it seems ideal for what I'm trying to do. Upon trying to use it though, it seems that the  object type for the query is being inferred from the type i'm trying to deserialize to. i.e. I have a class called Action, and ElasticLinq therefore thinks I want to return types of "Actions" and my URl ends up being http://stuff/actions/actions/_search. (Which is wrong. I don't even want to filter by a specific type necessarily).

In addition, all my property names are being lower-cased and therefore not matching anything. So Action has a property called "Name", but when the query is sent, the json object's property is "name" (with a small "n"). This means that it doesn't match anything, ever. Is there a way around this behavior?

**Comment by damieng** [comment]
You can absolutely change how that is handled. IElasticMapping is the interface that controls how we do that.

Even better the default ElasticMapping class actually has some constructor arguments that should take care of the scenarios you describe, specifically:

`var mapping = new ElasticMapping(camelCaseFieldNames: false, pluralizeTypeNames: false, camelCaseTypeNames:false);`

Anything more advanced and you should create your own class that inherits from ElasticMapping and overrides the behavior with what you want!

Please feel free to share any limitations of the Mapping interface you run into so we can address those.
