### ISSUE TITLE
Support for .NET 4.0 

### ISSUE THREAD

**Issue by doubret** [ElasticLINQ/ElasticLINQ#33]
How about adding support for .NET 4.0 ?
From what i see it should not be too difficult. I can take some time to look into it if you're interested.

**Comment by thequbit** [comment]
Would this just take a re-compile?  What about the current library isn't supported in a .Net 4.0 install?

**Comment by doubret** [comment]
It's not a matter of just retargetting / recompiling.
From what i see it uses .NET 4.5 features (IReadOnlyList<T>, IReadOnlyCollection<T>) and async/await keywords that are not available in .NET4 (at least not natively).

**Comment by thequbit** [comment]
Ahh, gotcha.  Should be pretty simple to identify what would need to be changed.  Although I don't know if there is enough demand to provide that level of backward compatibility.  Also testing could get messy.

**Comment by doubret** [comment]
Yes, it should be easy to migrate to .NET 4. Why do you say that testing could get messy ?

I played with the code all the afternoon, i changed a few things in the logging mecanism and added support for a few apis (Get, MultiGet, Source, IndexExists, and TypeExists).
I also played with the mapping mecanism, adding attribute based mapping directives, and found a few bugs in the elastic translator.

I don't know if i should create a new project from scratch or start from a fork.

**Comment by damieng** [comment]
.NET 4.0 should be pretty easy. We can have a .NET 4.0 and a .NET 4.5 project (we're going to want to support async/await).

We'd love to take some pull requests and work with you on these features and fixes.

**Comment by bradwilson** [comment]
FYI: You can't use async/await with the Async Targeting Pack for .NET 4.0, because it's broken with ASP.NET. Also, the HttpClient for .NET 4.0 is behind the times as well.

**Comment by doubret** [comment]
Maybe async/await could be a thin layer over the .NET 4.0 implementation. .NET 4.0 has support for Task so it should be easy to have the sync/async versions available in .NET 4.0 and provide async/await extensions for .NET 4.5.

This afternoon i changed a few things in the ElasticConnection class to control the access to the http client. I removed the property getter and added generic Get, Post and Head methods to handle the communication and serialization. This way i could easily add the pretty option to all queries through a ElasticOptions class and plug requests/responses tracing in a single place. 

I'll create a fork tomorrow so that i can send you pull requests.
Don't hesitate to contact me by mail if you want to discuss design or implementation.

**Comment by damieng** [comment]
I spent several hours looking at this and we decided the amount of changes and regressions we'd have to do wouldn't make sense at this time.
