### ISSUE TITLE
Support for querying several indices/types

### ISSUE THREAD

**Issue by doubret** [ElasticLINQ/ElasticLINQ#34]
Adding support for specifying indices and/or types to query.

Something like :

// query all indices and all types
context.Query<MyType>().Where(x => x.Prop > 123).Select(x => new { x.Prop1, x.Prop2 })....

// query on specific indices (all types)
context.Indices("index1", "index2", "index3").Query<MyType>().Where(x => x.Prop > 123).Select(x => new { x.Prop1, x.Prop2 })....

// query on specific types (all indices)
context.Types("type1", "type2", "type3").Query<MyType>().Where(x => x.Prop > 123).Select(x => new { x.Prop1, x.Prop2 })....

// query on specific indices and types
context.Indices("index1", "index2", "index3").Types("type1", "type2", "type3").Query<MyType>().Where(x => x.Prop > 123).Select(x => new { x.Prop1, x.Prop2 })....

Or :

var indices = new Indices("index1", "index2", "index3");
var types = new Types("type1", "type2", "type3");

// query all indices and all types
context.Query<MyType>().Where(x => x.Prop > 123).Select(x => new { x.Prop1, x.Prop2 })....

// query on specific indices (all types)
context.Query<MyType>(indices).Where(x => x.Prop > 123).Select(x => new { x.Prop1, x.Prop2 })....

// query on specific types (all indices)
context.Query<MyType>(types).Where(x => x.Prop > 123).Select(x => new { x.Prop1, x.Prop2 })....

// query on specific indices and types
context.Query<MyType>(indices, types).Where(x => x.Prop > 123).Select(x => new { x.Prop1, x.Prop2 })....

**Comment by damieng** [comment]
I think we'd need to see some more realistic samples to fully understand the use cases.

Indexes right now we have one-per-context/connection. If you set it to blank you get the first style. I'm not sure how common it is to need to query across indexes. As we get to an update model this could also complicate management of the documents.

[)amien

**Comment by doubret** [comment]
Using the same context to query different indices can be usefull.
I don't see any reason to force a user to create a connection and a context for every index to query.
Once we have a context that makes sense to be able to select the index to query, no ?

**Comment by damieng** [comment]
I get that we _can_ easily enable this I'm just trying to figure out if it's a good idea.

In the LINQ world a provider wouldn't access or update multiple databases in a single hit. Now it might be that indexes really are a different world from databases and that is just something we need to make clear.

There are a bunch of open questions that I think some real-world examples would help qualify:
1. Are the documents in the different indices always exactly the same or do they have slight differences? (We'd need to handle that)
2. How often would different indices be desired - is it when querying against type A I always want index B and C or is it for-this-particular-query-I-want-B-and-C?  (The latter is extremely fragile)
3. Once we implement saving would a user expect a SaveChanges() type call to affect multiple indexes?
4. Having multiple-index support means lookup-by-id and in-memory-identity-map both need to be index qualified. (Might be ok)

[)amien

**Comment by doubret** [comment]
I agree that indexes and databases are different, but LINQ is not only about databases, it's about querying data sources.
In my opinion, in the case of elasticsearch, the data source is the cluster, not a particular index.

Given the apis, elasticsearch supports single or multiple indices/types apis, a document always belong to only one index and one type. That's why indexing or updating are single index apis.
On the other hand searching is a multiple indices api because nothing prevents to search on several indices at the same time.

A document in a cluster is unique and it's primary key can be seen as the tuple [index, type, id](that's why elastic always returns index and type in the hits of a search). Being able to track a document is therefore not a problem. But that's not directly LINQ related, LINQ doesn't track objects itself, it's only used to query and doesn't know about inserts, updates or deletes.

If your goal is to create a full ORM, LINQ is only a small part of the job.

About your questions :
1. Querying multiple indices/types is peanuts, it just instructs elastic about the scope of the query. The first challenge is to define how to write and translate the query from an expression tree into an elastic search request. In the case of a similar type (or if the query only uses fields common across all documents) it is trivial. In the case of very different documents it's more complex but does it make sense ?
   The second challenge is materializing the results, this can be done using covariance and materialization dispatching according to the index/type of the hit.
2. In think that the scope of the search should not be part of the query. The same query should be executable on different scopes without changes. If you think about it, the request you send to elasticsearch is the same, it's just the endpoint url which is different.
3. I think your goal is to create an ORM because you mention SaveChanges. An ORM works by keeping an in memory snapshot of the entities that have been retrieved from the storage. It tracks the changes and when SaveChanges is called it is able to identify what has changed locally and reconcile these changes with the storage.
   For a database, when calling SaveChanges, the ORM can update several entities in several tables, and take care of foreign keys, etc.
   For an elasticsearch ORM it makes sense that a call to SaveChanges updates several documents in several indices/types. Once again, a document always belongs to a single index/type so it's not a problem.
4. Having single index support means the same thing.

I hope it makes sense ;)

**Comment by damieng** [comment]
I am aware of what an ORM is having been a developer at Microsoft on both LINQ to SQL and Entity Framework...

You can actually use multiple indexes right now by specifying a comma-separated list in the index property of the ElasticConnection.

**Comment by bradwilson** [comment]
Note that while this works today, it will probably not work once we move to add CUD operations (where we will have to mandate a single index, so we know which index to perform the CUD operations on).

**Comment by doubret** [comment]
Ok, i can understand your position.
