### ISSUE TITLE
Syntax for using facets

### ISSUE THREAD

**Issue by doubret** [ElasticLINQ/ElasticLINQ#36]
Hi,
I'm in the process of adding facet support in my project but i fail to find an elegant syntax to add facets to a linq query.
Can you please show me how you did it in ElasticLINQ ?
Thanks

**Comment by damieng** [comment]
We don't support all the facets yet, we support the ones that nicely map to LINQ.

The facet operations are: Min, Max, Sum, Average (mean), Count, LongCount (count)

Any of these can be against one of four facet types:
- **statistical** - Anything other than a count that either doesn't use a group-by or group-by's against a constant value
- **term_stats** Anything other than a count that DOES use a group-by field
- **term** Using only a count against a group-by
- **filter** Using counts without a group-by (either a whole count or has a where/predicate specified)

e.g. `var results = db.Products.GroupBy(p => p.Category).Select(g => new { g.Key, Sales = g.Sum(z => z.Sold), Active = g.Count(z => z.Active));`

Note: We use the older Elasticsearch facets API right now for broader compatibility. Switching to the newer one will not break our API as we are hiding behind LINQ.

**Comment by doubret** [comment]
Ah ok, i see.

You're using facets to translate the GroupBy call.
Nice trick.

Thank you.
