### ISSUE TITLE
Query cannot contain AND or OR clauses

### ISSUE THREAD

**Issue by doubret** [ElasticLINQ/ElasticLINQ#37]
The following request generates an invalid query :

``` csharp
context.Query<tata>().Query(x => x.Int == 1 && x.String == "tutu")
```

The query generated is:

``` json
{"query":{"and":[{"term":{"int":1}},{"term":{"string":"tutu"}}]},"timeout":"10s"}
```

The AND and OR operators are not supported by ES at the query level (only at the filter level).

One solution is to replace AND and OR (and NOT, etc...) by bool queries.
Another one is to create a filtered query and put the criterias in the filter.

**Comment by damieng** [comment]
I don't think a bool query is an option as users might put a combination of && || and braces. FilteredQuery is probably the way to go although needs a bit of thought on how/where to promote query up to filtered query in the code.

**Comment by doubret** [comment]
bool query(filter) is the same as AND and OR filters, it just can do more, but not less (you can replace all your AND and OR filters with BOOL, it will do the same thing).
on the other hand, bool queries can combine your AND and OR queries in a single query, but the logic to combine them right is probably more complex than combining AND and OR operations.
anyway, query vs filter is what ES is all about... hierarchical queries, something that flat SQL can hardly do.

**Comment by damieng** [comment]
I don't think a bool query filter is advanced enough to handle things like (a == 1) || (b == 2 && c == 3) ?

**Comment by doubret** [comment]
Nope, a single bool query cannot handle things like this, but you can nest two bool queries as you would nest OR and AND.
Though, (a == 1) && (b == 2 || c == 3) can be translated in a single bool query instead of an AND and an OR.
