### ISSUE TITLE
Range filter does not handle two checks to the same field for the same operation

### ISSUE THREAD

**Issue by doubret** [ElasticLINQ/ElasticLINQ#38]
I found a bug with the range filter.

If i have more than one comparison for a given property, the generated filter groups the comparisons in the same range filter.
But if i put twice the same comparison operator, the json fails to serialize (duplicate property name).

eg : .Where(x => x.Int > 4 && x.Int > 3)

By the way, i tried to implement range grouping logic in my project but it's not an easy task, as nodes in the expression tree can be anywhere. Can you hint me on how you did it in ElasticLINQ ?

**Comment by damieng** [comment]
I'll get this fixed - in response to your other question there is no easy way to translate expression trees. I'd recommend reading Matt Warren's series at http://blogs.msdn.com/b/mattwar/archive/2008/11/18/linq-links.aspx and also consider using an abstraction/helper like Re-linq used by EF7 and NHibernate) to make things easier.

**Comment by doubret** [comment]
Thanks for the link, it looks very interesting.
I'll give a look at Re-linq also.

Can you give me a few hints on how you do it in ElasticLINQ ?
I have read most of the code but i admit that i didn't spot this detail.

Thanks.

**Comment by damieng** [comment]
The checks for selection criteria happen in CriteriaExpressionVisitor. It combines the expressions within  a Where or a Query clause into a CriteriaExpression which consists of a translated and optimized tree of ICriteria nodes that represent the structure in Elasticsearch.

**Comment by doubret** [comment]
In my project i do it in two passes:

1 - Evalution pass : i traverse all the tree and evaluate what can/must be evaluated before translating the expression tree to ES.
2 - Translation pass : i traverse the tree a second time, depth first, and create the ES query on the fly. As i bubble up the tree i can easily merge AND and OR operations but for range i don't see an easy way to merge range filters (except storing them in a dictionary with the field as key but i don't like the idea).

Now i can imagine adding an 3rd pass to "optimize" the ES query tree but i would prefer avoid it if possible, and have these little optimizations done in the 2nd pass.

I saw you have a similar aproach (at least 2 passes, maybe 3 ?) but you modify the tree in the 2nd pass (the Criteria expressions), i modify it only in the 1st pass.
Do you merge the range filters when converting form the rewritten expression tree (after the 2nd pass) to the ES query ?

**Comment by doubret** [comment]
Ok, i'll try to look in the code tomorrow and see where it happens.
Thanks

**Comment by doubret** [comment]
Ok it's fixed, but
.Where(x => x.Int > 4 && x.Int > 3)

Could reduce to 
.Where(x => x.Int > 3)

Instead of ANDing both conditions.
