### ISSUE TITLE
Query with locally evaluated constant fails to translate

### ISSUE THREAD

**Issue by damieng** [ElasticLINQ/ElasticLINQ#44]
If writing Query statement that includes either a direct boolean constant, e.g.:

``` csharp
var query = db.Products.Query(p => true);
```

or more likely something that has evaluated to true using the partial evaluator, e.g.:

``` csharp
Product current = null;
var query = db.Products.Query(p => current == null || p.ParentId == current.Id);
```

Then a translation error will occur as the binary expression can not be translated today.

**Comment by doubret** [comment]
You can translate it into a (match_all) filter.
Idem for x => false (not(match_all)).

There are also the cases (x => some conition && true) or (x => some conition && false) (idem with ||). In this case it could be temptating to simplify the filters (some condition && false will always be false...) but i'm not sure it's a good idea because it will mess the score. The match_all aproach seems to be more robust.

**Comment by damieng** [comment]
The plan is to optimize them out of the criteria as you mentioned in your second option. I can't see how it would affect the score as these optimizations are only if they evaluate entirely locally - i.e. have no reference to product.

**Comment by doubret** [comment]
As you can associate a score boost to a query and later filter by score, removing a query that boosts the score will change the results.
Let's take this :
{
  "query": {
    "bool": {
      "should": [
        {
          "term": {
            "prop": 123
          }
        },
        {
          "match_all": {}
        }
      ],
      "boost": 2
    }
  }
}

As you can see, the query will return all the documents but with score boosting. In c# it could write something like this :
.Query(x => (x.prop == 123 || true), boost: 2)
In this case, removing the criteria has an effect.

If you don't plan to support scoring it's maybe not a problem to remove the filters though.

**Comment by doubret** [comment]
For exemple :

This query returns some documents :
{
  "min_score": 1.4,
  "query": {
    "bool": {
      "should": [
        {
          "term": {
            "Int": 2
          }
        },
        {
          "match_all": {}
        }
      ]
    }
  }
}

But this one returns nothing :
{
  "min_score": 1.4
}
