### ISSUE TITLE
Support Count and LongCount top-level operations

### ISSUE THREAD

**Issue by damieng** [ElasticLINQ/ElasticLINQ#5]
Support:
- query.Count()
- query.Count(x => x.Boolean)
- query.LongCount()
- query.LongCount(x => x.Boolean)

Note that the version containing the boolean predicate overloads will also need to add a sub-filter to the facet containing the translated predicate.

**Comment by damieng** [comment]
Count operations are already supported through the GroupBy(x => 1).Select(x => x.Count()) but we should support the top level syntax as well.

**Comment by damieng** [comment]
Implemented.

**Comment by JayXun** [comment]
When CountElasticMaterializer._Materialize_ returns an int as an object, ElasticQueryProvider._Execute_ throws an InvalidCastException when attempting to cast the boxed int to a long.

Using
`return (TResult)ChangeType(Execute(expression), typeof(TResult));`
to force conversion.
