### ISSUE TITLE
Supported .Net and Elasticsearch versions?

### ISSUE THREAD

**Issue by prabhu** [ElasticLINQ/ElasticLINQ#59]
This looks like an interesting project. I just tried using this with .Net 4.5 and Elasticsearch 1.5.2 and went no where. A simple select operation returned no data. The code doesn't throw any exception if the uri is invalid etc.

Occasionally, I see this error on Elasticsearch

[2015-04-28 16:06:48,404][DEBUG][http.netty               ] [Test Master 1] Caught exception while handling client http traffic, closing connection [id: 0x656aeb85, /0:0:0:0:0:0:0:1:50924 => /0:0:0:0:0:0:0:1:9200] java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)

Should I assume that this combination of .Net and ES is not supported?

**Comment by damieng** [comment]
.NET 4.5 and ElasticSearch 1.5 are definitely supported and working here at Centurylink Cloud.

Are you going through a proxy server or using authentication?

Also could you try running Fiddler to see what the request and response for a query look like?

Thanks!

**Comment by prabhu** [comment]
Hi damien,

I have the elasticsearch locally. There is no authentication involved.

My connection details look like this.
private static ElasticConnection connection = new ElasticConnection(new Uri("http://localhost:9200"), null, null, null, POLICY_INDEX, null);
        private static ElasticContext context = new ElasticContext(connection);

I also tried with just new Uri("") without anything else.

**Comment by damieng** [comment]
Are you able to get anything back in your browser entering the url http://localhost:9200

**Comment by prabhu** [comment]
Yes. I am able to use NEST to perform insert and retrieval etc.

**Comment by damieng** [comment]
What does you query and domain class look like?  e.g. 

``` csharp
public class Customer {
  public int Id { get; set}
  public string Name { get; set; }
}
...
var query = context.Query<Customer>().Where(c => c.Id > 6);
```

By default we'll attempt to map the T (in this case Customer) to the es type name 'customer'. If this isn't how your types are mapped you'd also get zero results.  

If you set a breakpoint after the query but before a ToList / AsEnumerable and put query.ToQueryInfo() in the debug watch window you will see the body and uri parameters generated for your query.

**Comment by diskman** [comment]
I have got same issue on 1.5.2
I am trying to query for bzp type:
`
var res3 = db.Query<Bzp>().Where(p => p.data_publikacji >= DateTime.Now.AddDays(-5) && p.data_publikacji < now.AddDays(5).Date);
            var str = res3.ToQueryInfo().Query;
`
There should be more than 600 results but it is 0.
`
"{\"filter\":{\"range\":{\"data_publikacji\":{\"gte\":\"2015-04-24T00:00:00+02:00\",\"lt\":\"2015-05-04T00:00:00+02:00\"}}},\"timeout\":\"10s\"}"
`
Type name is Bzp and in ES it is bzp

**Comment by prabhu** [comment]
Ok I have managed to solve my problem. The problem was the automatic camel casing by the context. Debugging by looking at the info helped in my case. Thank you.

**Comment by damieng** [comment]
Glad that solved your problem prabhu.

Diskman, what does the Uri it is generating look like?  (the .Uri property of ToQueryInfo())

**Comment by damieng** [comment]
Original problem resolved. Diskman, if you are having issues still please open another issue.
