### ISSUE TITLE
Produce a single binary using Profile111

### ISSUE THREAD

**Issue by damieng** [ElasticLINQ/ElasticLINQ#73]
Rather than produce two binaries, one for .NET 4.5 and one for Profile259 produce a single library that can be used instead. This reduces the build time, number of unit tests and halves the test surface area.

The reason these were separate is because Profile259 requires a HttpClient and the one from Microsoft.Net.Http dragged in Microsoft.Bcl and Microsoft.Bcl.Build and we did not want to add those to mainline 4.5 scenarios.

By switching to Profile111 we lose Windows Phone Silverlight 8 but gain the ability to use a single HttpClient without additional baggage.

**Comment by thequbit** [comment]
I'm sorry if this is a stupid question, but what is Profile259 and Profile111?  Are those .Net specific things, or ElasicLINQ specific?

**Comment by damieng** [comment]
Profile259 and Profile111 are Portable Class Library terms for what platforms a library can support.  

By switching to Profile111 we can have a single .dll/nuget package that will work for .NET 4.5 desktop, Windows 10 Universal, Windows 8, Windows Phone 8.1 apps, Xamarin 2 etc.  It's the broadest profile that doesn't require an additional HttpClient dependency.
