### ISSUE TITLE
Ability to specify multiple indexes and ignore unavailable?

### ISSUE THREAD

**Issue by ejsmith** [ElasticLINQ/ElasticLINQ#74]
I am currently taking a look at your library and it looks really nice. I have document types that are using date based indexes and I need to do a query across many indexes and also have the ability to ignore any indexes that I specify that are unavailable.

Also, I guess your library is only for querying the data and doesn't support the ability to save documents?

**Comment by damieng** [comment]
Hi Eric, been a while!

It should be possible to extend the query mechanism to dispatch to multiple indexes and combine the results without too much difficulty but yes, right now it doesn't do that.  ElasticRequestProcessor.cs is where the multiple HTTP Requests would be initiated and the results combined. The only thing that requires some thought is how the index names would be generated - that would likely be a subclass of ElasticMapping that knows certain queries map to certain date indexes and could do things like check for certain fields in the selection and map them to index ranges much like Kibana.

The library is indeed query only - our plan is to integrate with Elasticsearch.NET in the near future which would then provide us with all the non-LINQ parts and update facilities. One thing we do need to check is that their mapping mechanism is rich enough to support the LINQ model.

**Comment by ejsmith** [comment]
Yeah, long time! :-)

Elasticsearch handles all the results combining on the server side, we would just need the ability to specify multiple indexes in the request. I don't think it would be too big of a change. I am going to investigate the feasibility of using your lib a bit more and then maybe I will submit a pull request for the feature.

I like the idea of combining this library with the official one. I'm not a huge fan of the official client. Would be really nice to get a LINQ implementation included.

**Comment by damieng** [comment]
Sounds good.  They actually split the official library into two parts - Elasticsearch.NET is just concerned with providing a basic REST-style API with connection management over Elasticsearch while NEST is a builder for their own query language. We'd be able to provide an alternative to NEST for the majority of scenarios while using the same underlying core for connections etc.

**Comment by badcommandorfilename** [comment]
Hi,

Just in case it helps anyone, I had a similar issue where the ElasticConnection will throw (after retrying for a few seconds) if you query an index that doesn't exist. I suppose my expectation was that it would just return an empty set - so I added a [check](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-exists.html) before each query:

```csharp
        async Task<bool> IndexExists(Uri endpoint, string index)
        {
            var uri = new UriBuilder(endpoint);
            uri.Path = index;
            using (var message = new HttpRequestMessage(HttpMethod.Head, uri.Uri))
            using (var response = await Client.SendAsync(message).ConfigureAwait(false))
            {
                return response.IsSuccessStatusCode;
            }
        }
```

I think this project is really great so I'll try to find the time to contribute this behavior back to the repo. 

It might make more sense for this to happen in the RetryPolicy or ElasticConnection to either create missing indexes on a failed request or return an empty IQueryable if the index is missing...
