### ISSUE TITLE
Creating context is needlessly complex or home page example is poor

### ISSUE THREAD

**Issue by dotnetchris** [ElasticLINQ/ElasticLINQ#77]
For the first time ever i heard of this project. This is what I'm greeted with:

`var db = new ElasticContext(new ElasticConnection(new Uri("http://myserver:9200")));`

If this is really the standard usage scenario how in the world is it not just:

`var db = new ElasticContext("http://myserver:9200");`

If the expectation that connections are short lived or anything else, this example is very poor and needs to be shown with an expected usage.

**Comment by damieng** [comment]
This is an minimal example. In reality you will want to specify indexes, timeouts etc. all which go on the connection. In the future we will also likely have two different connection classes - the current HttpClient based one and the Elasticsearch.net connection pooling one.

The normal pattern for LINQ based contexts is to create your own that takes care of all of this and exposes the domain object query points as properties, e.g.

``` csharp
public class MyElasticContext : ElasticContext
{ 
  public MyElasticContext() : base(new ElasticConnection(ConfigSettings.MyElasticUrl))
  {
  }

  public IQueryable<Customer> Customers { get { return base.Query<Customer>(); } }
}
```

The connections can be as short or long-lived as you like. Unlike EF and LINQ to SQL there is no caching, staleness of data or memory growth to contend with.
