### ISSUE TITLE
Support cross complex type's properties queries

### ISSUE THREAD

**Issue by AlexzundeR** [ElasticLINQ/ElasticLINQ#81]
Sample query: 

```
elasticContext.Query<Document>()
  .Where(e => e.Types.Any(e1=>e1.ParentTypes.Contains("ConcreteType"))

// Types - collection of complex type DocumentType
// ParentTypes - collection of strings

// Which must be mapped to elastic query:
{
    "query" : {
        "filtered" : {
            "filter" : {
                "term" : {
                    "types.parentTypes" : "ConcreteType"
                }
            }
        }
    },
    "timeout" : "10s"
}
```

Now that and similary queries does not supported, but I try to realize it by self and end with fail. With mapper, that map FieldInfos to fileld, I can't realize bypassing of limitation of propertyType in expressionTree, that prevents me of creating of TermsCriteria with properties "Types" and "ParentTypes" (I have exception that field "Types" with type of IEnumerable<DocumentType> hasn't property "ParentTypes"). 
What can I do with this? Or maybe you can realize it by yourself.

**Comment by damieng** [comment]
The support for sub-collection operations is quite minimal right now so I suspect that pattern isn't yet recognized and mapped.  I could take a look but it's not going to be a few days.  If you want to dive in I suspect that CriteriaExpressionVisitor would need to be modified - it would need to detect the various operations within an Any operation and return a CriteriaExpression that represented those operations.

**Comment by AlexzundeR** [comment]
https://github.com/CenturyLinkCloud/ElasticLINQ/pull/82

Please see this pull request. I didn't create tests now cause I think you must watch it before.
