### ISSUE TITLE
Upgrade to Json.NET v7

### ISSUE THREAD

**Issue by Dreamwalker666** [ElasticLINQ/ElasticLINQ#87]
Title says it all.

**Comment by damieng** [comment]
Are you seeing any issues? Right now it specifies v6 but works just fine if given v7.  That would seem the best option rather than forcing v7 yet not using any of the new features.

**Comment by Dreamwalker666** [comment]
I hit an issue due to package dependencies been v7 in other libraries.  Maybe change the nuspec to allow v6-7 for the dependency.  Since you mention it works fine if the v7 dll is present.  And I do agree not upgrading would be better overall. (Great lib btw!)

**Comment by damieng** [comment]
I'll definitely look into making sure it's happy with v6 and v7. Glad the library is working out for you. Feel free to send feedback on usability/missing features.

**Comment by damieng** [comment]
Hmm, now v8 is out...

**Comment by damieng** [comment]
Updated to v9 in master.
