### ISSUE TITLE
IQueryable<T>.Union Should be Implemented

### ISSUE THREAD

**Issue by efaruk** [ElasticLINQ/ElasticLINQ#88]
Currently we are having NotSupportedException, but I'm almost sure this can be done with ElasticSearch Multi Query and this will be perfect ;)

**Comment by damieng** [comment]
Hi, can you give an example of what you imagine the Elasticsearch query would look like for a union?

**Comment by efaruk** [comment]
Something like this:

select \* from Student where (School = 'Levent') OR (School ='4. Levent' and Class='3.') OR (Class !=2.)

elastic version:

POST student/_search
{
   "query": {
      "bool": {
         "should": [
            {
               "term": {
                  "school": {
                     "value": "Levent"
                  }
               }
            },
            {
               "bool": {
                  "must": [
                     {
                        "term": {
                           "school": {
                              "value": "4. Levent"
                           }
                        }
                     },
                     {
                        "term": {
                           "class": {
                              "value": "3."
                           }
                        }
                     }
                  ]
               }
            },
            {
               "bool": {
                  "must_not": [
                     {
                        "term": {
                           "school": {
                              "value": "2."
                           }
                        }
                     }
                  ]
               }
            }
         ]
      }
   }
}

**Comment by damieng** [comment]
I don't see any union in your LINQ query or corresponding Elastic query.

**Comment by efaruk** [comment]
The "OR" operator...

**Comment by damieng** [comment]
The OR operator should work just fine today both as a filter and a query and has unit test coverage.  Can you share an actual LINQ query that fails with that not supported message?

**Comment by efaruk** [comment]
Yep OR works really fine, but I mean: union should work like OR operator. Currently UNION not supported by ElasticLINQ...

**Comment by damieng** [comment]
What do you mean by Union? Please post a simple LINQ query that would fail.

**Comment by efaruk** [comment]
Do you think are we starting over!? Never mind...
