### ISSUE TITLE
Build w/ Xamarin

### ISSUE THREAD

**Issue by Adron** [ElasticLINQ/ElasticLINQ#9]
@SaintGimp @bradwilson @AdeMiller @aweiker @brannon & all.

I opened up the project with Xamarin (I try to build everything from this, then I know it works across all systems). The issues that popped up are reference issues with 
![errors](https://f.cloud.github.com/assets/278870/2388537/e4745134-a942-11e3-8028-c79c7a03c280.png)

I think there my be some solutions available here http://components.xamarin.com/view/json.net but I'm a bit time pressed to get this tested. Not sure what cycles others might have, but might be worth a go. At some point I'd be happy to roll any changes/fixes back into the library.

I know [Xamarin](http://xamarin.com/) support isn't probably a priority but I have a project I'd love to pull this into and it's 100% Linux & Xamarin stuff (they're doing a bunch of cross dev w/ Android, iOS & Ubuntu Server).  ;)

Cheers,
@adron

Update: Added a possible fix by updating the Nuget packages via Xamarin here: https://github.com/CenturyLinkCloud/ElasticLINQ/pull/10

In the testing library it however throws an issue with the accessibility of some of the variables but all the references are fixed.

**Comment by bradwilson** [comment]
Merged in 5d49b74f810c17a3a95ac41132275bbc7f904377. If there are any more issues, please re-open the issue.
