### ISSUE TITLE
Any plans to support Elastic 2 ?

### ISSUE THREAD

**Issue by dmitrynovik** [ElasticLINQ/ElasticLINQ#99]
Hi,

This is a very handy project, but, as I tried it with Elastic 2 and as expected it fails.
Do you have plans to support it?

**Comment by damieng** [comment]
What operations did you try that failed? I was only aware of GroupBy would not work as facets are deprecated and need to move to Aggregates.

**Comment by dmitrynovik** [comment]
found the issue was with the Elastic Mapping - the default naming conventions did not match with elastic (e.g. I found all typenames in Elastic became lowercase). Had to create my own IElasticMapping implementation

**Comment by damieng** [comment]
The basic implementations have some simple properties you can set to enable/disable the various lowercasing.
